name: CI/CD

on: push

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.
      - name: run install and build
        run: |
          npm install
          npm run build